---
title: "CTD_Processing"
author: "Dylan Titmuss"
date: "10/12/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

This script processes the RBR data files (.xlsx and .txt) from the May and October 2021 Georges Bank RSA trips.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages
```{r}
library(tidyverse)
library(chron)
library(oce)

setwd("~/Repos/ScallopRSA2021")
```

## Load rsk files & convert to csv
```{r}
## No data from sites 006, 012, 016, 022, 030, 081, 111, 114 ##

# Chronological sites 001-060; includes 001-057 + 060-062 + 066-068 (no data from sites 006, 012, 016, 022, 030)
may1rsk <- read.rsk("data/CTD_raw/RSA_20210504_060.rsk")
may1 <- as.ctd(may1rsk)
write.ctd(may1, "data/CTD_raw/may1.csv")
may1 <- read.csv("data/CTD_raw/may1.csv") %>%
  slice(-c(1:17)) %>%
  mutate(data = R.oce.file.exported.at.time.2021.11.08.20.39.34.UTC) %>%
  select(-R.oce.file.exported.at.time.2021.11.08.20.39.34.UTC)

# Chronological sites 065-113; includes 058-059 + 063-065 + 069-113 (no data from sites 081, 111)
may2rsk <- read.rsk("data/CTD_raw/RSA_20210506_113.rsk")
may2 <- as.ctd(may2rsk)
write.ctd(may2, "data/CTD_raw/may2.csv")
may2 <- read.csv("data/CTD_raw/may2.csv") %>%
  slice(-c(1:17)) %>%
  mutate(data = R.oce.file.exported.at.time.2021.11.08.20.39.44.UTC) %>%
  select(-R.oce.file.exported.at.time.2021.11.08.20.39.44.UTC)

# No data from site 114

may_combined <- rbind(may1, may2)
write.csv(may_combined, "data/CTD_raw/CTD_allMay.csv", row.names = FALSE)
```

## Split csv file into channels & combine
```{r}
mayCTD <- read.csv("data/CTD_raw/CTD_allMay.csv")

time <- mayCTD %>%
 slice(which(row_number() %% 9 == 1))
conductivity <- mayCTD %>%
 slice(which(row_number() %% 9 == 2))
temperature <- mayCTD %>%
 slice(which(row_number() %% 9 == 3))
pressure <- data.frame("data" = c(may1rsk@data[["pressure"]],
                                  may2rsk@data[["pressure"]]))
optode_temp <- mayCTD %>%
 slice(which(row_number() %% 9 == 5))
dissolvedO2conc <- mayCTD %>%
 slice(which(row_number() %% 9 == 6))
sea_pressure <- mayCTD %>%
 slice(which(row_number() %% 9 == 7))
depth <- mayCTD %>%
 slice(which(row_number() %% 9 == 8))
salinity <- mayCTD %>%
 slice(which(row_number() %% 9 == 0))

# combine channels into dataframe
mayCTD <- time %>%
  mutate(Time = data,
         Conductivity_mS.cm = conductivity$data,
         Temperature_degC = temperature$data,
         Pressure_dbar = pressure$data,
         OptodeTemp_degC = optode_temp$data,
         DissolvedO2Conc_umol.l = dissolvedO2conc$data,
         SeaPressure_dbar = sea_pressure$data,
         Depth_m = depth$data,
         Salinity_PSU = salinity$data) %>%
  select(-data) %>%
  separate(Time, c("Date", "Time"), " ") %>%
  mutate(Date = as.Date(Date, format = "%Y-%m-%d")) %>%
  filter(Date >= "2021-05-02")

write.csv(mayCTD, "data/CTD_raw/CTD_allMay.csv", row.names = FALSE)
```

## Load October data
```{r}
## No data from sites 022, 023, 104 ##

# Sites 001-021
oct1 <- read.csv("data/CTD/CSV_raw/RSA_20211006_021.csv", skip = 1, header = TRUE) %>%
  separate(Time, c("Date", "Time"), " ") %>%
  mutate(Date = as.Date(Date, format = "%Y-%m-%d")) %>%
  filter(Date >= "2021-10-05")
  
# No data from sites 022-023

# Chronological sites 024-064; includes 024-068
oct2 <- read.csv("data/CTD/CSV_raw/RSA_20211008_064.csv", skip = 1, header = TRUE) %>%
  separate(Time, c("Date", "Time"), " ")

# Sites 069-114 (no data from site 104)
oct3 <- read.csv("data/CTD/CSV_raw/RSA_20211010_114.csv", skip = 1, header = TRUE) %>%
  separate(Time, c("Date", "Time"), " ")

oct_combined <- rbind(oct1, oct2, oct3)
write.csv(oct_combined, "data/CTD/CTD_allOct.csv", row.names = FALSE)
```










## Figuring out which files need loading to capture all data
```{r}
file007_008 <- read.csv("data/CTD_raw/RSA_20211005_007+008.csv", skip = 1, header = TRUE) %>%
  slice(-c(1:2)) %>%
  mutate(Minute = substring(Time, 0, 16)) %>%
  separate(Time, c("Date", "Time"), " ") %>%
  mutate(Timestamp = chron(dates = Date, times = Time, format = c('Y-m-d', 'h:m:s')))
minutes007008 <- as.data.frame(unique(file007_008$Minute))
plot(file007_008$Depth ~ file007_008$Timestamp)
#includes sites 001-008

file009 <- read.csv("data/CTD_raw/RSA_20211005_009.csv", skip = 1, header = TRUE) %>%
  slice(-c(1:2)) %>%
  mutate(Minute = substring(Time, 0, 16))
minutes009 <- as.data.frame(unique(file009$Minute))
#discard; includes part of site 001 only

file010 <- read.csv("data/CTD_raw/RSA_20211005_010.csv", skip = 1, header = TRUE) %>%
  slice(-c(1:2)) %>%
  mutate(Minute = substring(Time, 0, 16))
minutes010 <- as.data.frame(unique(file010$Minute))
#discard; includes site 001 & part of site 002 only

file011 <- read.csv("data/CTD_raw/RSA_20211005_011.csv", skip = 1, header = TRUE) %>%
  slice(-c(1:2)) %>%
  mutate(Minute = substring(Time, 0, 16))
minutes011 <- as.data.frame(unique(file011$Minute))
#discard; includes sites 001-007 only

file012 <- read.csv("data/CTD_raw/RSA_20211005_012.csv", skip = 1, header = TRUE) %>%
  slice(-c(1:2)) %>%
  mutate(Minute = substring(Time, 0, 16)) %>%
  separate(Time, c("Date", "Time"), " ") %>%
  mutate(Timestamp = chron(dates = Date, times = Time, format = c('Y-m-d', 'h:m:s')))
minutes012 <- as.data.frame(unique(file012$Minute))
plot(file012$Depth ~ file012$Timestamp)
#discard; includes sites 001-008 & slightly after only

file013 <- read.csv("data/CTD_raw/RSA_20211005_013.csv", skip = 1, header = TRUE) %>%
  slice(-c(1:2)) %>%
  mutate(Minute = substring(Time, 0, 16)) %>%
  separate(Time, c("Date", "Time"), " ") %>%
  mutate(Timestamp = chron(dates = Date, times = Time, format = c('Y-m-d', 'h:m:s')))
minutes013 <- as.data.frame(unique(file013$Minute))
plot(file013$Depth ~ file013$Timestamp)
#includes sites 001-009

file014 <- read.csv("data/CTD_raw/RSA_20211005_014.csv", skip = 1, header = TRUE) %>%
  slice(-c(1:2)) %>%
  mutate(Minute = substring(Time, 0, 16)) %>%
  separate(Time, c("Date", "Time"), " ") %>%
  mutate(Timestamp = chron(dates = Date, times = Time, format = c('Y-m-d', 'h:m:s')))
minutes014 <- as.data.frame(unique(file014$Minute))

plot(file014$Depth ~ file014$Timestamp)
#includes sites 001-014! woohoo!

file015 <- read.csv("data/CTD_raw/RSA_20211005_015.csv", skip = 1, header = TRUE) %>%
  slice(-c(1:2)) %>%
  mutate(Minute = substring(Time, 0, 16))
minutes015 <- as.data.frame(unique(file015$Minute))
#includes sites 001-015

file021 <- read.csv("data/CTD_raw/RSA_20211006_021.csv", skip = 1, header = TRUE) %>%
  slice(-c(1:2)) %>%
  mutate(Minute = substring(Time, 0, 16)) %>%
  separate(Time, c("Date", "Time"), " ") %>%
  mutate(Timestamp = chron(dates = Date, times = Time, format = c('Y-m-d', 'h:m:s')))
minutes021 <- as.data.frame(unique(file021$Minute))
#includes sites 001-021

plot(file021$Depth_m ~ file021$Timestamp) #21 sites

file022 <- read.csv("data/CTD_raw/RSA_20211006_022.csv", skip = 1, header = TRUE) %>%
  slice(-c(1:2)) %>%
  mutate(Minute = substring(Time, 0, 16)) %>%
  separate(Time, c("Date", "Time"), " ") %>%
  mutate(Timestamp = chron(dates = Date, times = Time, format = c('Y-m-d', 'h:m:s')))
minutes022 <- as.data.frame(unique(file022$Minute))
#discard; includes sites 001 & 002 only

file023 <- read.csv("data/CTD_raw/RSA_20211006_023.csv", skip = 1, header = TRUE) %>%
  slice(-c(1:2)) %>%
  mutate(Minute = substring(Time, 0, 16)) %>%
  separate(Time, c("Date", "Time"), " ") %>%
  mutate(Timestamp = chron(dates = Date, times = Time, format = c('Y-m-d', 'h:m:s')))
minutes023 <- as.data.frame(unique(file023$Minute))
#discard; includes sites 001-009 only

file024 <- read.csv("data/CTD_raw/RSA_20211006_024.csv", skip = 1, header = TRUE) %>%
  mutate(Minute = substring(Time, 0, 16)) %>%
  separate(Time, c("Date", "Time"), " ") %>%
  mutate(Timestamp = chron(dates = Date, times = Time, format = c('Y-m-d', 'h:m:s')))
minutes024 <- as.data.frame(unique(file024$Minute))
#includes site 24

file064 <- read.csv("data/CTD_raw/RSA_20211008_064.csv", skip = 1, header = TRUE) %>%
  mutate(Minute = substring(Time, 0, 16)) %>%
  separate(Time, c("Date", "Time"), " ") %>%
  mutate(Timestamp = chron(dates = Date, times = Time, format = c('Y-m-d', 'h:m:s')))
minutes064 <- as.data.frame(unique(file064$Minute))
#includes sites 024-068 (last chronologically is 064)

plot(file064$Depth_m ~ file064$Timestamp) #45 sites

file069 <- read.csv("data/CTD_raw/RSA_20211008_069.csv", skip = 1, header = TRUE) %>%
  mutate(Minute = substring(Time, 0, 16)) %>%
  separate(Time, c("Date", "Time"), " ") %>%
  mutate(Timestamp = chron(dates = Date, times = Time, format = c('Y-m-d', 'h:m:s')))
minutes069 <- as.data.frame(unique(file069$Minute))
#includes site 069

file114 <- read.csv("data/CTD_raw/RSA_20211010_114.csv", skip = 1, header = TRUE) %>%
  mutate(Minute = substring(Time, 0, 16)) %>%
  separate(Time, c("Date", "Time"), " ") %>%
  mutate(Timestamp = chron(dates = Date, times = Time, format = c('Y-m-d', 'h:m:s')))
minutes114 <- as.data.frame(unique(file114$Minute))
#includes sites 069-114, no data from site 104

plot(file114$Depth_m ~ file114$Timestamp) #45 sites
```
