#!/bin/bash
#SBATCH --partition=compute
#SBATCH --job-name="Bayesian1"
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=36
#SBATCH --mem=32gb
#SBATCH --time=00:30:00
#SBATCH --output=help.out
cd /vortexfs1/scratch/dylan.titmuss

echo "Running on node(s): $SLURM_NODELIST starting in: `pwd`"
date

module load R
module load JAGS

Rscript --vanilla help.R
