---
title: "ScallopData"
author: "Dylan Titmuss"
date: "12/9/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load packages
```{r setup}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(marmap)
library(sf)
library(numform)
library(viridis)
```

## Load scallop data
```{r}
setwd("~/Desktop/Repos/ScallopRSA2021")

mayPlaco <- read.csv("./data/MayScallopData.csv") %>%
  mutate(Site = str_extract(ScallopID, "^.{3}(?=_)")) %>%
  select(-Mus_Boat2_g, -Gon_Boat2_g, -Man_Boat2_g) %>%
  mutate(Month = "May")

octPlaco <- read.csv("./data/OctScallopData.csv") %>%
  mutate(Site = str_extract(ScallopID, "^.{3}(?=_)")) %>%
  mutate(Month = "Oct")

# check number of scallops per site
table(mayPlaco$Site)
table(octPlaco$Site)

Placo <- rbind(mayPlaco, octPlaco) %>%
  mutate(WetMus_g = as.numeric(WetMus_g)) %>%
  mutate(LinDensity = ShellWt_g / ShellHt_mm)
```

## Load station data
```{r}
may <- read.csv("~/Desktop/Repos/ScallopRSA2021/data/MayCruiseData.csv") %>%
  rename(Lat = Latitude_degrees_start,
         Long = Longitude_degrees_start) %>%
  filter(Cast == "Bottom") %>%
  mutate(Tow = ifelse(is.na(Tow_start_time), "N", "Y")) %>%
  mutate(Month = "May") %>%
  mutate(Station = as.character(f_pad_zero(Station))) # add leading zeros to station numbers

oct <- read.csv("~/Desktop/Repos/ScallopRSA2021/data/OctCruiseData.csv") %>%
  rename(Lat = Latitude_degrees_start,
         Long = Longitude_degrees_start) %>%
  filter(Filtered == "",
         Cast == "Bottom") %>%
  select(-Filtered, -DIC.TA.Ratio, -DO_sat) %>%
  mutate(Tow = ifelse(is.na(Tow_start_time), "N", "Y")) %>%
  mutate(Month = "Oct") %>%
  mutate(Station = as.character(f_pad_zero(Station))) # add leading zeros to station numbers

seasons <- rbind(may, oct) %>%
  rename(Temp = Temperature)
```

## Combine scallop data and station geo data
```{r}
seasonsPlaco <- Placo %>%
  rename(Station = Site) %>%
  group_by(Month, Station) %>%
  summarise(ShellHt_mm = mean(ShellHt_mm, na.rm = TRUE),
            ShellWt_g = mean(ShellWt_g, na.rm = TRUE),
            WetMus_g = mean(WetMus_g, na.rm = TRUE),
            LinDensity = mean(LinDensity, na.rm = TRUE))

seasons <- seasons %>%
  filter(Tow == "Y",
         Tow_abundance != 0)
```

## Add CO2 sys data
```{r}
seasCarb <- carb(flag = 15,                               # 15 = ALK & DIC given
                var1 = seasons$TA[!is.na(seasons$Temp)] / 10^6,  # in mol/kg
                var2 = seasons$DIC[!is.na(seasons$Temp)] / 10^6, # in mol/kg
                S = seasons$Salinity[!is.na(seasons$Temp)],
                T = seasons$Temp[!is.na(seasons$Temp)],          # in deg C
                Patm = seasons$Pressure[!is.na(seasons$Temp)] * 0.098692326671601,
                                                         # in atm
                P = seasons$SeaPressure[!is.na(seasons$Temp)] / 10,   # in bar
                k1k2 = "l",                              # l = Lueker et al. (2000)
                                                         # kf: unspecified b/c low temps
                ks = "d",                                # d = Dickson (1990)
                b = "l10")                               # l10 = Lee et al. (2010)

# combine scallop & carb data
r <- 1
for(i in c(1:5, 7:44)) {
  seasons$pH[i] <- seasCarb$pH[r]
  seasons$pCO2[i] <- seasCarb$pCO2[r]
  seasons$OmegaAragonite[i] <- seasCarb$OmegaAragonite[r]
  seasons$OmegaCalcite[i] <- seasCarb$OmegaCalcite[r]
  r <- r + 1
}

for(i in 1:nrow(seasons)) {
  if(is.na(seasons$Temp[i])) {
    seasons$pH[i] <- NA
    seasons$pCO2[i] <- NA
    seasons$OmegaAragonite[i] <- NA
    seasons$OmegaCalcite[i] <- NA
  }
}

seasonsPlaco <- right_join(seasons, seasonsPlaco, by = c("Station", "Month"))
```

## Add chem data to full Placo df
```{r}
Placo$OmegaAragonite <- NA

for(i in 1:nrow(Placo)) {
  Placo$OmegaAragonite[i] <- seasonsPlaco$OmegaAragonite[seasonsPlaco$Station == Placo$Site[i]]
}
```

## Plot size parameters
```{r}
ggplot(Placo, aes(x = Site, y = ShellHt_mm, col = Month)) +
  geom_boxplot(position = position_dodge2(preserve = "single")) +
  scale_color_manual(values = c("chartreuse3", "royalblue")) +
  labs(y = "Shell Height (mm)") +
  theme_bw() +
  theme(panel.grid.major.x = element_blank())

ggplot(Placo, aes(x = Site, y = ShellWt_g / ShellHt_mm, col = Month)) +
  geom_boxplot(position = position_dodge2(preserve = "single")) +
  scale_color_manual(values = c("chartreuse3", "royalblue")) +
  ylim(0, 2.3) +
  labs(y = expression("Shell Weight : Shell Height (g mm"^-1*")")) +
  theme_bw() +
  theme(panel.grid.major.x = element_blank())

ggplot(Placo, aes(x = Site, y = WetMus_g, col = Month)) +
  geom_boxplot(position = position_dodge2(preserve = "single")) +
  scale_color_manual(values = c("chartreuse3", "royalblue")) +
  labs(y = "Muscle Wet Weight (g)") +
  theme_bw() +
  theme(panel.grid.major.x = element_blank())

ggplot(Placo, aes(x = ShellHt_mm, y = WetMus_g, col = Month)) +
  geom_point() +
  scale_color_manual(values = c("chartreuse3", "royalblue")) +
  labs(x = "Shell Height (mm)", y = "Muscle Wet Weight (g)") +
  theme_bw() +
  theme(panel.grid.major.x = element_blank())

ggplot(Placo[Placo$Month == "May", ], aes(x = ShellHt_mm, y = WetMus_g, col = Site)) +
  geom_point() +
  labs(x = "Shell Height (mm)", y = "Muscle Wet Weight (g)") +
  theme_bw() +
  theme(panel.grid.major.x = element_blank())

ggplot(seasonsPlaco, aes(x = ShellHt_mm, y = WetMus_g, col = OmegaAragonite)) +
  geom_point() +
  scale_colour_viridis() +
  labs(x = "Shell Height (mm)", y = "Muscle Wet Weight (g)") +
  theme_bw() +
  theme(panel.grid.major.x = element_blank())

ggplot(Placo[!is.na(Placo$OmegaAragonite), ], aes(x = ShellHt_mm, y = WetMus_g, col = OmegaAragonite)) +
  geom_point() +
  scale_colour_viridis() +
  labs(x = "Shell Height (mm)", y = "Muscle Wet Weight (g)") +
  theme_bw() +
  theme(panel.grid.major.x = element_blank())
```

## Convert coordinates
```{r}
chd <- substr(seasons$Lat, 3, 3)[1]

# convert latitude from DM to DD
Lat_split_may <- str_split_fixed(seasons$Lat, chd, 2) %>%
  as.data.frame()
Lat_split_may$V2 <- str_remove_all(Lat_split_may$V2, pattern = "'") %>%
  as.numeric()
Lat_split_may$V2 <- Lat_split_may$V2/60
Lat_split_may$V1 <- as.numeric(Lat_split_may$V1)

seasons$Lat <- Lat_split_may$V1 + Lat_split_may$V2

# convert longitude from DM to DD
Long_split_may <- str_split_fixed(seasons$Long, chd, 2) %>%
  as.data.frame()
Long_split_may$V2 <- str_remove_all(Long_split_may$V2, pattern = "'") %>%
  as.numeric()
Long_split_may$V2 <- Long_split_may$V2/60
Long_split_may$V1 <- as.numeric(Long_split_may$V1)

seasons$Long <- -(Long_split_may$V1 + Long_split_may$V2)
```

## Create simple features obj
```{r}
# create geometry column in data frame from lat/long data
for(i in 1:nrow(seasonsPlaco)) {
  seasonsPlaco$geometry[i] <- st_point(x = c(seasonsPlaco$Long[i], seasonsPlaco$Lat[i])) %>%
    st_sfc(crs = 4326)
}

# create an sf object from data frame
seasonsPlaco_sf <- st_sf(seasonsPlaco, crs = 4326)
```

## Create map
```{r}
# create base map with NOAA data
GB_bathy <- getNOAA.bathy(lon1 = -70.5, lon2 = -66, lat1 = 40, lat2 = 42.5, resolution = 1)

ggbathy <- GB_bathy %>%
  fortify() %>%
  mutate(lat = y, long = x, depth = z) %>%
  select(-c(x, y, z)) %>%
  mutate(depth_bins = cut(depth, breaks = c(0, -30, -55, -75, -90, -120, -150, -180, -780, -1380, -1980, -2580, -3180, -Inf)))

sf_use_s2(FALSE)

# get mass coastline
mass <- read_sf("/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/gshhg-shp-2.3.7/GSHHS_shp/f/GSHHS_f_L1.shp") %>%
  st_make_valid() %>%
  st_crop(xmin = -71, xmax = -66, ymin = 40, ymax = 43)

map <- ggplot() +
  geom_raster(data = ggbathy, aes(long, lat, fill = depth_bins), interpolate = TRUE, alpha = 0.75) +
  scale_fill_manual(values = c("#08306B", "#084184", "#08519C", "#1561A9", "#2171B5", "#3282BE", "#4292C6", "#57A0CE", "#6BAED6", "#85BCDC", "#9ECAE1", "#B2D3E8", "#C6DBEF"),
                    na.value = "#C6DBEF",
                    guide = "none") +
  geom_sf(data = mass, fill = "darkgrey", colour = "black") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(breaks = c(40, 41, 42), expand = c(0, 0)) +
  coord_sf(xlim = c(-70.5, -66), ylim = c(40, 42.5), crs = st_crs(4326)) +
  theme_bw() +
  theme(axis.title = element_blank())
```

## Add station data to map
```{r}
map +
  geom_point(data = stationsPlaco_sf, aes(x = Long, y = Lat, size = ShellHt_mm)) +
  scale_size_continuous(name = "Mean Shell\nHeight (mm)",
                        range = c(1, 6),
                        limits = c(80, 140),
                        breaks = c(80, 100, 120, 140))

map +
  geom_point(data = stationsPlaco_sf, aes(x = Long, y = Lat, size = WetMus_g), shape = 18) +
  scale_size_continuous(name = "Muscle Wet\nWeight (g)",
                        range = c(2, 6),
                        limits = c(10, 50))

map +
  geom_point(data = stationsPlaco_sf, aes(x = Long, y = Lat, size = Tow_abundance), shape = 17)
```

## Old plots
```{r}
heights <- map +
  geom_sf(data = stations_sf, aes(size = ShellHt_mm, fill = Tow, shape = Tow), inherit.aes = FALSE) +
  geom_sf_text(data = stations_sf, aes(label = Station, colour = Tow), nudge_x = 0, nudge_y = 0.09, size = 3.5, inherit.aes = FALSE) +
  scale_size_continuous(range = c(2, 7), name = "Mean Shell Height (mm)") +
  #scale_fill_manual(values = c("white", "black"), guide = "none") +
  #scale_shape_manual(values = c(21, 22), guide = "none") +
  #scale_colour_manual(values = c("white", "black"), guide = "none") +
  labs(title = "Variation in Scallop Shell Size Across Georges Bank") +
  coord_sf(crs = st_crs(4326)) +
  theme(plot.title = element_text(size = 17, face = "bold", hjust = 0.5),
        axis.text = element_text(size = 13),
        legend.title = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 12))

heights <- map +
  geom_sf(data = stations_sf, aes(size = ShellHt_mm), inherit.aes = FALSE) +
  geom_sf_text(data = stations_sf, aes(label = Station), nudge_x = 0, nudge_y = 0.09, size = 3.5, inherit.aes = FALSE) +
  scale_size_continuous(range = c(2, 7), name = "Mean Shell Height (mm)") +
  labs(title = "Variation in Scallop Shell Size Across Georges Bank") +
  coord_sf(xlim = c(-70.5, -66), ylim = c(40, 42.5), crs = st_crs(4326)) +
  theme(plot.title = element_text(size = 17, face = "bold", hjust = 0.5),
        axis.text = element_text(size = 13),
        legend.title = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 12))

heights

densities <- map +
  geom_sf(data = stations_sf, aes(size = LinDensity, fill = Tow, shape = Tow), inherit.aes = FALSE) +
  geom_sf_text(data = stations_sf, aes(label = Station, colour = Tow), nudge_x = 0, nudge_y = 0.09, size = 3.5, inherit.aes = FALSE) +
  scale_size_continuous(range = c(2.5, 7.5), name = "Mean Ratio of Shell Weight\nto Shell Height (g/mm)", guide = guide_legend(override.aes = list(shape = 22, fill = "white"))) +
  scale_fill_manual(values = c("white", "black"), guide = "none") +
  scale_shape_manual(values = c(22, 21), guide = "none") +
  scale_colour_manual(values = c("white", "black"), guide = "none") +
  labs(title = "Variation in Scallop Shell Linear Density Across Georges Bank") +
  coord_sf(crs = st_crs(4326)) +
  theme(plot.title = element_text(size = 17, face = "bold", hjust = 0.5),
        axis.text = element_text(size = 13),
        legend.title = element_text(size = 14, face = "bold"),
        legend.text = element_text(size = 12))

densities
```






## Register Google API key
```{r, include = FALSE}
register_google(key = "AIzaSyBvvS_nvTml09h56OWd0Oniktayi0L8WDU")
```

## Load satellite map
```{r}
library(ggmap)

GB_map <- get_map(c(-68.5247, 40.8155), maptype = "satellite", zoom = 7, source = "google")

map <- ggmap(GB_map) +
  coord_sf(crs = st_crs(4326)) +
  xlim(c(-71, -65.5)) +
  scale_y_continuous(breaks = c(40, 41, 42), limits = c(39.5, 42.5)) +
  theme(axis.title = element_blank())

map
```
