---
title: "MayCruiseChemistry"
author: "Dylan Titmuss"
date: "1/19/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

This script visualizes the chemistry data from the May RSA cruise.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, root.dir = "~/Desktop/Repos/ScallopRSA2021")

register_google(key = "AIzaSyBvvS_nvTml09h56OWd0Oniktayi0L8WDU")
```

## Load packages
```{r}
library(tidyverse)
library(ggmap)
library(sf)
library(numform)
library(sp)
library(viridis)
```

## Load data
```{r}
TA <- read.csv("./data/Station_TA.csv") %>%
  mutate(Station = str_extract(BottleID, "[0-9]{3}"),
         Cast = rep(NA, 228))

for(i in 1:length(TA$BottleID)) {
  c <- str_extract(TA$BottleID[i], ".$")
  if(c == "A") {
    TA$Cast[i] <- "Bottom"
  } else if (c == "B") {
    TA$Cast[i] <- "Surface"
  }
}

TA$Cast[1] <- "Surface" # correct for flipped bottles
TA$Cast[2] <- "Bottom"
```

## Visualize data
```{r}
ggplot(TA, aes(x = Cast, y = TA_avg)) +
  geom_boxplot() +
  theme_bw()

ggplot(TA, aes(x = Salinity, y = TA_avg)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme_bw()

ggplot(TA, aes(x = Salinity, y = TA_avg, col = Cast)) +
  geom_point() +
  scale_color_manual(values = c("black", "red")) +
  theme_bw()
```

## Load satellite map
```{r}
GB_map <- get_map(c(-68.5247, 40.8155), maptype = "satellite", zoom = 7, source = "google")

map <- ggmap(GB_map) +
  coord_sf(crs = st_crs(4326)) +
  xlim(c(-71, -65.5)) +
  scale_y_continuous(breaks = c(40, 41, 42), limits = c(39.5, 42.5)) +
  theme(axis.title = element_blank())

map
```

## Load station data & convert coordinates
```{r}
may <- read.csv("./data/MayCruiseData.csv") %>%
  rename(mayLat = Latitude_degrees_start,
         mayLong = Longitude_degrees_start,
         depth = Depth_meters) %>%
  select(Station, Cast, Bottle_ID, mayLat, mayLong, depth)

# convert latitude from DM to DD
Lat_split_may <- str_split_fixed(may$mayLat, chd, 2) %>%
  as.data.frame()
Lat_split_may$V2 <- str_remove_all(Lat_split_may$V2, pattern = "'") %>%
  as.numeric()
Lat_split_may$V2 <- Lat_split_may$V2/60
Lat_split_may$V1 <- as.numeric(Lat_split_may$V1)

may$mayLat <- Lat_split_may$V1 + Lat_split_may$V2

# convert longitude from DM to DD
Long_split_may <- str_split_fixed(may$mayLong, chd, 2) %>%
  as.data.frame()
Long_split_may$V2 <- str_remove_all(Long_split_may$V2, pattern = "'") %>%
  as.numeric()
Long_split_may$V2 <- Long_split_may$V2/60
Long_split_may$V1 <- as.numeric(Long_split_may$V1)

may$mayLong <- -(Long_split_may$V1 + Long_split_may$V2)
```

## Add chemistry data to stations df
```{r}
stations <- stations %>%
  mutate(Station = as.character(f_pad_zero(Station))) # add leading zeros to station numbers

stations <- left_join(TA, stations, by = "Station")
```

## Add station points to map
```{r}
stations_SPDF <- SpatialPointsDataFrame(coords = stations[ , c("Long","Lat")],
                                        data = stations[ ,c("Long", "Lat", "Station", "Cast", "Tow",
                                                            "TA_avg", "Salinity")],
                                        proj4string = CRS("+init=epsg:4326"))

stations_sf <- st_as_sf(stations_SPDF)
stations_sf <- st_transform(stations_sf, crs = 4326)

bottom_sf <- stations_sf %>%
  filter(Cast == "Bottom")

bottomTA <- map +
  geom_sf(data = bottom_sf, aes(size = TA_avg, colour = TA_avg), inherit.aes = FALSE) +
  #geom_sf_text(data = bottom_sf, aes(label = Station), nudge_x = 0, nudge_y = 0.09, size = 3.5, inherit.aes = FALSE) +
  scale_colour_viridis(limits = c(2150, 2300), option = "rocket") +
  labs(title = "Bottom Alkalinity") +
  coord_sf(crs = st_crs(4326))

bottomTA

surface_sf <- stations_sf %>%
  filter(Cast == "Surface")

surfaceTA <- map +
  geom_sf(data = surface_sf, aes(size = TA_avg, colour = TA_avg), inherit.aes = FALSE) +
  #geom_sf_text(data = surface_sf, aes(label = Station), nudge_x = 0, nudge_y = 0.09, size = 3.5, inherit.aes = FALSE) +
  scale_colour_viridis(limits = c(2150, 2300), option = "rocket") +
  labs(title = "Surface Alkalinity") +
  coord_sf(crs = st_crs(4326))

surfaceTA

bottomSal <- map +
  geom_sf(data = bottom_sf, aes(size = Salinity, colour = Salinity), inherit.aes = FALSE) +
  #geom_sf_text(data = bottom_sf, aes(label = Station), nudge_x = 0, nudge_y = 0.09, size = 3.5, inherit.aes = FALSE) +
  scale_colour_viridis(limits = c(32, 35), option = "rocket") +
  labs(title = "Bottom Salinity") +
  coord_sf(crs = st_crs(4326))

bottomSal

surfaceSal <- map +
  geom_sf(data = surface_sf, aes(size = Salinity, colour = Salinity), inherit.aes = FALSE) +
  geom_sf_text(data = surface_sf, aes(label = Station), nudge_x = 0, nudge_y = 0.09, size = 3.5, inherit.aes = FALSE) +
  scale_colour_viridis(limits = c(32, 35), option = "rocket") +
  labs(title = "Surface Salinity") +
  coord_sf(crs = st_crs(4326))

surfaceSal
```

## marmap version (no polygons)
```{r}
library(marmap)
# Create base map with NOAA data
GB_bathy <- getNOAA.bathy(lon1 = -70.5, lon2 = -66, lat1 = 40, lat2 = 42.5, resolution = 1)

plot(GB_bathy, image = TRUE, land = TRUE, n = 0, lwd = 1,
     bpal = list(c(min(GB_bathy), -175, "#08306B","#08519C", "#2171B5", "#4292C6"), 
            c(-175, 0, "#4292C6", "#6BAED6", "#9ECAE1", "#C6DBEF"), 
            c(0, max(GB_bathy), "grey")))
```

## raster version
```{r}
ggbathy <- GB_bathy %>%
  fortify() %>%
  mutate(lat = y, long = x, depth = z) %>%
  select(-c(x, y, z)) %>%
  mutate(depth_bins = cut(depth, breaks = c(0, -30, -55, -75, -90, -120, -150, -180, -780, -1380, -1980, -2580, -3180, -Inf)))

ggplot() +
  geom_raster(data = ggbathy, aes(long, lat, fill = depth_bins), interpolate = TRUE, alpha = 0.75) +
  scale_fill_manual(values = c("#08306B", "#084184", "#08519C", "#1561A9", "#2171B5", "#3282BE", "#4292C6", "#57A0CE", "#6BAED6", "#85BCDC", "#9ECAE1", "#B2D3E8", "#C6DBEF")) +
  theme(legend.position = "none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank())
```

## ggOceanMaps version
```{r}
library(ggOceanMaps)
basemap(limits = c(-70.5, -66, 40, 42.5), rotate = TRUE, grid.col = NA, bathymetry = TRUE)

basemap(limits = c(-70.5, -66, 40, 42.5), rotate = TRUE, grid.col = NA, bathymetry = TRUE, bathy.style = "contour_blues")
```






## Load Oct datasheet
```{r}
oct <- read.csv("./data/OctoberCruiseData.csv") %>%
  rename(octLat = Latitude_degrees_start,
         octLong = Longitude_degrees_start,
         depth = Depth_meters) %>%
  select(Station, Cast, octLat, octLong, depth)

# convert latitude from DM to DD
Lat_split_oct <- str_split_fixed(oct$octLat, chd, 2) %>%
  as.data.frame()
Lat_split_oct$V2 <- str_remove_all(Lat_split_oct$V2, pattern = "'") %>%
  as.numeric()
Lat_split_oct$V2 <- Lat_split_oct$V2/60
Lat_split_oct$V1 <- as.numeric(Lat_split_oct$V1)

oct$octLat <- Lat_split_oct$V1 + Lat_split_oct$V2

# convert longitude from DM to DD
Long_split_oct <- str_split_fixed(oct$octLong, chd, 2) %>%
  as.data.frame()
Long_split_oct$V2 <- str_remove_all(Long_split_oct$V2, pattern = "'") %>%
  as.numeric()
Long_split_oct$V2 <- Long_split_oct$V2/60
Long_split_oct$V1 <- as.numeric(Long_split_oct$V1)

oct$octLong <- -(Long_split_oct$V1 + Long_split_oct$V2)
```

## Compare May vs Oct coordinates
```{r}
joined <- left_join(may, oct, by = c("Station", "Cast"), suffix = c("_may", "_oct")) %>%
  mutate(diffLat = abs(mayLat - octLat), diffLong = abs(mayLong - octLong))

max(joined$diffLat)
max(joined$diffLong)
which(joined$diffLat > 0.05)
which(joined$diffLong > 0.05)
```
