---
title: "QC_Check"
author: "Dylan Titmuss"
date: "1/25/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages
```{r}
library(tidyverse)
library(numform)
library(sf)
```

## Load RSA data
```{r}
setwd("~/Desktop/Repos/ScallopRSA2021")

may <- read.csv("./data/MayCruiseData.csv") %>%
  rename(Lat = Latitude_degrees_start,
         Long = Longitude_degrees_start,
         Depth = Depth_m_CTD,
         Temp = Temperature,
         DO = Dissolved_oxygen) %>%
    select(Date, Station, Cast, BottleID, Lat, Long,
         Depth, Temp, Pressure, SeaPressure, Salinity,
         DIC, TA, DO) %>%
  mutate(Station = as.character(f_pad_zero(Station))) # add leading zeros to stations
```

## Convert coordinates from DM to DD
```{r}
chd <- substr(may$Lat, 3, 3)[1]

# latitude
Lat_split_may <- str_split_fixed(may$Lat, chd, 2) %>%
  as.data.frame()
Lat_split_may$V2 <- str_remove_all(Lat_split_may$V2, pattern = "'") %>%
  as.numeric()
Lat_split_may$V2 <- Lat_split_may$V2/60
Lat_split_may$V1 <- as.numeric(Lat_split_may$V1)

may$Lat <- Lat_split_may$V1 + Lat_split_may$V2
rm(Lat_split_may)

# longitude
Long_split_may <- str_split_fixed(may$Long, chd, 2) %>%
  as.data.frame()
Long_split_may$V2 <- str_remove_all(Long_split_may$V2, pattern = "'") %>%
  as.numeric()
Long_split_may$V2 <- Long_split_may$V2/60
Long_split_may$V1 <- as.numeric(Long_split_may$V1)

may$Long <- -(Long_split_may$V1 + Long_split_may$V2)
rm(Long_split_may)
rm(chd)
```

## Set region bounds
```{r}
# minLat <- min(may$Lat) - 0.5
# maxLat <- max(may$Lat) + 0.5
# minLon <- min(may$Long) - 0.5
# maxLon <- max(may$Long) + 0.5
```

## Load QC data
```{r}
QC <- read.csv("./data/bottle_data_DIC_prepared.csv") %>%
  filter(TALK_flag != 3) #%>%
  # filter(!is.na(TALK),
  #        Latitude >= minLat,
  #        Latitude <= maxLat,
  #        Longitude >= minLon,
  #        Longitude <= maxLon)
```

## Prop-prop plots (Supp. Figs. 1-2)
```{r}
ggplot() +
  geom_point(data = QC, aes(x = DIC, y = TALK, shape = "historical data", col = "historical data"), alpha = 0.5) +
  geom_point(data = may, aes(x = DIC, y = TA, shape = "May 2021 cruise", col = "May 2021 cruise"), alpha = 0.5) +
  geom_point(data = oct, aes(x = DIC, y = TA, shape = "Oct 2021 cruise", col = "Oct 2021 cruise"), alpha = 0.5) +
  scale_shape_manual(values = c(1, 16, 16), name = "Data Source") +
  scale_colour_manual(values = c("black", "coral", "royalblue"), name = "Data Source") +
  labs(x = expression("DIC (μmol kg"^-1*")"), y = expression("TA (μmol kg"^-1*")")) +
  theme_bw() +
  theme(legend.title = element_text(face = "bold"),
        legend.position = c(0.88, 0.14))

ggsave("SuppFig1.png", width = 6.5, height = 4.6, units = "in", dpi = 600, bg = "#ffffff")

ggplot() +
  geom_point(data = QC, aes(x = Salinity, y = TALK, shape = "historical data", col = "historical data"), alpha = 0.5) +
  geom_point(data = may, aes(x = Salinity, y = TA, shape = "May 2021 cruise", col = "May 2021 cruise"), alpha = 0.5) +
  geom_point(data = oct, aes(x = Salinity, y = TA, shape = "Oct 2021 cruise", col = "Oct 2021 cruise"), alpha = 0.5) +
  scale_shape_manual(values = c(1, 16, 16), name = "Data Source") +
  scale_colour_manual(values = c("black", "coral", "royalblue"), name = "Data Source") +
  labs(x = expression("Salinity (PSU)"), y = expression("TA (μmol kg"^-1*")")) +
  theme_bw() +
  theme(legend.title = element_text(face = "bold"),
        legend.position = c(0.88, 0.14))

ggsave("SuppFig2.png", width = 6.5, height = 4.6, units = "in", dpi = 600, bg = "#ffffff")
```

## Map of QC data sites
```{r}
for(i in 1:nrow(QC)) {
  QC$geometry[i] <- st_point(x = c(QC$Longitude[i], QC$Latitude[i])) %>%
    st_sfc(crs = 4326)
}

QC_sf <- st_sf(QC, crs = 4326)

ggplot() +
  geom_sf(data = QC_sf) +
  geom_sf(data = GB_sf, fill = NA, linewidth = 0.4, linetype = "dashed") +
  geom_sf(data = mass, fill = "darkgrey", colour = NA) +
  #scale_y_continuous(breaks = c(40, 41, 42, 43)) +
  #coord_sf(xlim = c(-71, -65.5), ylim = c(39.5, 43), expand = FALSE) +
  theme_bw()
```






## Load QC data - NOT THIS
```{r}
QC <- read.csv("./data/bottle_satellite_data_clean.csv") %>%
  filter(Month == 4 | Month == 5) %>%
  filter(Latitude > 40 & Latitude < 42.5) %>%
  filter(Longitude < -66 & Longitude > -70) %>%
  select(Date, Latitude, Longitude, Depth_bottom, Depth, Salinity, Temperature,
         Oxygen, DIC, TA, bottom_depth) %>%
  rename(Lat = Latitude,
         Long = Longitude,
         Temp = Temperature) %>%
  mutate(Depth_ratio = ifelse(!is.na(Depth_bottom), Depth / Depth_bottom, Depth / bottom_depth)) %>%
  mutate(Cast = ifelse(Depth_ratio < 0.07, "Surface",
                       ifelse(Depth_ratio > 0.80, "Bottom", NA)))

QC$Cast[5] <- "Surface"
```
