---
title: "Salinity_Processing"
author: "Dylan Titmuss"
date: "12/7/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(gsw)
```

## Load data
```{r}
setwd("~/Desktop/Repos/ScallopRSA2021")

mayCTD <- read.csv("./data/salinity/may_salinity_CTD.csv")
may_bottle <- read.csv("./data/salinity/may_salinity_bottles.csv")
mayBottomData <- read.csv("./data/MayCruiseData_12-13-21.csv") %>%
  filter(Cast == "Deep") %>%
  arrange(Station)
```

## Calculate CTD offset
```{r}
for (i in 1:33) {
  k <- may_bottle$Station[i]
  s <- mayCTD[mayCTD$Station == k, 4]
  print(c(k, s))
}

# remove 12 & 81 -- no CTD data (indices 5 & 8)

station <- rep(NA, 31)
CTD_sal <- rep(NA, 31)
bottle_sal <- rep(NA, 31)
offset <- rep(NA, 31)

for (i in c(1:4, 6:7, 9:33)) {
  k <- may_bottle$Station[i]
  station[i] <- k
  CTD_sal[i] <- mayCTD[mayCTD$Station == k, 4]
  bottle_sal[i] <- may_bottle[i, 2]
  offset[i] <- CTD_sal[i] - bottle_sal[i]
}

comparison <- as.data.frame(cbind(station, bottle_sal, CTD_sal, offset))

mean(offset, na.rm = TRUE) # 0.0196791
median(offset, na.rm = TRUE) # 0.01988623
```

## Plot CTD data with bottle data
```{r}
ggplot(data = comparison, aes(x = station, y = CTD_sal)) +
  geom_point() +
  geom_point(aes(y = bottle_sal, col = "red")) +
  ylim(32.5, 35) +
  scale_color_discrete(labels = "bottle\nsample") +
  theme_bw() +
  theme(legend.title=element_blank())

plot(comparison$bottle_sal ~ comparison$CTD_sal)
abline(0, 1)
plot(comparison$offset ~ comparison$bottle_sal)
abline(h = 0, lty = 2)

# uncertainty in CTD = 0.001 mS/cm
gsw_SP_from_C(35.001, 7, 46.0566) - gsw_SP_from_C(35, 7, 46.0566) # ~0.0011 PSU

# CTD salinity consistently slightly higher than bottle salinity -- let's do a correction
```

## Correct CTD data given bottle data
```{r}
lm1 <- lm(bottle_sal ~ CTD_sal, comparison)
summary(lm1) # bottle = 1.003579(CTD) - 0.138245 (bins start @ 1.0m)

mayCTD$BottomSal_Corr <- 1.003579 * mayCTD$BottomSalinity - 0.138245

# check new offset
CTD_sal_corr <- rep(NA, 31)
corr_offset <- rep(NA, 31)

for (i in c(1:4, 6:7, 9:33)) {
  k <- may_bottle$Station[i]
  CTD_sal_corr[i] <- mayCTD[mayCTD$Station == k, 7]
  corr_offset[i] <- CTD_sal_corr[i] - bottle_sal[i]
}

comparison <- as.data.frame(cbind(comparison, CTD_sal_corr, corr_offset))

mean(corr_offset, na.rm = TRUE) # 0.000005858112
mean(abs(corr_offset), na.rm = TRUE) # 0.006372453

plot(comparison$bottle_sal ~ comparison$CTD_sal_corr)
abline(0, 1)
plot(comparison$corr_offset ~ comparison$bottle_sal)
abline(h = 0, lty = 2)

ggplot(data = comparison, aes(x = station, y = CTD_sal_corr)) +
  geom_point() +
  geom_point(aes(y = bottle_sal, col = "red")) +
  ylim(32.5, 35) +
  scale_color_discrete(labels = "bottle\nsample") +
  theme_bw() +
  theme(legend.title=element_blank())

# looks better!

mayCTD$SurfaceSal_Corr <- 1.003579 * mayCTD$SurfaceSalinity - 0.138245
```

## Extract CTD depths
```{r}
CTDdepth <- rep(NA, 114)

for (i in c(1:106)) {
  k <- mayCTD$Station[i]
  CTDdepth[k] <- mayCTD$CTDDepth[i]
}
```

## Check station assignments using depths
```{r}
radarDepth <- mayBottomData$Depth_meters

depthCheck <- as.data.frame(cbind(mayBottomData$Station, radarDepth, CTDdepth)) %>%
  mutate(Diff = radarDepth - CTDdepth) %>%
  mutate(Check = abs(Diff) > 5, Check2 = abs(Diff) > 3)

which(depthCheck$Check == TRUE) # all CTD depth readings are within 5m of recorded radar depth
which(depthCheck$Check2 == TRUE) # all but two CTD depths are within 3m of recorded radar depth

# station assignments look correct!
```

## Write corrected salinity values to file
```{r}
BottomSal_Corr <- rep(NA, 114)
SurfaceSal_Corr <- rep(NA, 114)

for (i in 1:length(mayCTD$Station)) {
  k <- mayCTD$Station[i]
  BottomSal_Corr[k] <- mayCTD$BottomSal_Corr[i]
  SurfaceSal_Corr[k] <- mayCTD$SurfaceSal_Corr[i]
}

# remove duplicate instance of RSA_021A
which(may_bottle$BottleID == "RSA_021A")

may_bottle <- may_bottle %>%
    filter(!row_number() %in% 39)

# add extra bottle sal values as replacements
for (i in 1:length(may_bottle$BottleID)) {
  b <- may_bottle$BottleID[i]
  k <- as.numeric(str_remove(str_extract(b, "[0-9]{3}"), "^0+"))
  c <- str_extract(b, ".$")
  if(c == "A") {
    BottomSal_Corr[k] <- may_bottle[may_bottle$BottleID == b, 2]
  } else if (c == "B") {
    SurfaceSal_Corr[k] <- may_bottle[may_bottle$BottleID == b, 2]
  }
}

Station <- rep(mayBottomData$Station, 2)
Cast <- c(rep("Bottom", 114), rep("Surface", 114))
CTD_depth <- rep(CTDdepth, 2)
Salinity_Corr <- c(BottomSal_Corr, SurfaceSal_Corr)

may_corrected <- as.data.frame(cbind(Station, Cast, CTD_depth, Salinity_Corr)) %>%
  mutate(Station = as.integer(Station)) %>%
  arrange(Station)

write.csv(may_corrected, "./data/salinity/may_salinity_corrected.csv", row.names = FALSE)
```






## Check surface salinity values against sal-alk relationship
```{r}
setwd("~/Desktop/Repos/ScallopRSA2021/TA_processing")

TA <- read.csv("Station_TA.csv") %>%
  mutate(Station = str_extract(BottleID, "0[0-9]{2}")) %>%
  mutate(Cast = rep(NA, 103))

for(i in 1:length(TA$BottleID)) {
  c <- str_extract(TA$BottleID[i], ".$")
  if(c == "a" | c == "A") {
    TA$Cast[i] <- "Bottom"
  } else if (c == "b" | c == "B") {
    TA$Cast[i] <- "Surface"
  }
}

TA$Cast[1] <- "Surface" # correct for flipped bottles
TA$Cast[2] <- "Bottom"

TA %>%
  filter(Cast == "Bottom") %>%
  ggplot(aes(x = Salinity, y = TA_avg)) +
    geom_point() +
    geom_smooth(method = "lm") +
    ylim(c(2100, 2300)) +
    theme_bw()

ggplot(TA, aes(x = Salinity, y = TA_avg, col = Cast)) +
  geom_point() +
  scale_color_manual(values = c("black", "red")) +
  ylim(c(2100, 2300)) +
  theme_bw()
```






#### Check salinity cut-off using bottle values
```{r}
mayCTD0.5 <- read.csv("./data/salinity/may_salinity_CTD_0-5.csv")
mayCTD1 <- read.csv("./data/salinity/may_salinity_CTD_1.csv")
mayCTD1.5 <- read.csv("./data/salinity/may_salinity_CTD_1-5.csv")
mayCTD2 <- read.csv("./data/salinity/may_salinity_CTD_2.csv")
mayCTD2.5 <- read.csv("./data/salinity/may_salinity_CTD_2-5.csv")
mayCTD3 <- read.csv("./data/salinity/may_salinity_CTD_3.csv")
mayCTD3.5 <- read.csv("./data/salinity/may_salinity_CTD_3-5.csv")

cutoff <- as.data.frame(cbind(1:114, rep(NA, 114), rep(NA, 114), rep(NA, 114), rep(NA, 114), rep(NA, 114), rep(NA, 114), rep(NA, 114), rep(NA, 114)))
colnames(cutoff) <- c("Station", "BottleSal", "CTDSal0.5", "CTDSal1", "CTDSal1.5", "CTDSal2", "CTDSal2.5", "CTDSal3", "CTDSal3.5")

for (i in 1:length(may_bottle$BottleID)) {
  b <- may_bottle$BottleID[i]
  k <- as.numeric(str_remove(str_extract(b, "[0-9]{3}"), "^0+"))
  c <- str_extract(b, ".$")
  if(c == "B") {
    cutoff$BottleSal[k] <- may_bottle[may_bottle$BottleID == b, 2]
  }
}

for (i in 1:length(mayCTD$Station)) {
  k <- mayCTD$Station[i]
  cutoff$CTDSal0.5[k] <- 1.003579 * mayCTD0.5$SurfaceSalinity[i] - 0.138245
  cutoff$CTDSal1[k] <- 1.003579 * mayCTD1$SurfaceSalinity[i] - 0.138245
  cutoff$CTDSal1.5[k] <- 1.003579 * mayCTD1.5$SurfaceSalinity[i] - 0.138245
  cutoff$CTDSal2[k] <- 1.003579 * mayCTD2$SurfaceSalinity[i] - 0.138245
  cutoff$CTDSal2.5[k] <- 1.003579 * mayCTD2.5$SurfaceSalinity[i] - 0.138245
  cutoff$CTDSal3[k] <- 1.003579 * mayCTD3$SurfaceSalinity[i] - 0.138245
  cutoff$CTDSal3.5[k] <- 1.003579 * mayCTD3.5$SurfaceSalinity[i] - 0.138245
}

cutoff <- na.omit(cutoff)
```
